version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - tessi
- package-ecosystem: cargo
  directory: "/native/pdf_to_text"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
